config/routes.rb
Rails.application.routes.draw do
  get 'prefectures/new'
  get 'histricalfigures/new'
  get 'histricalfigures/index'

  resources :prefectures
  # root 'items#new'

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "top#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/histrical_figure.rb
class HistricalFigure < ApplicationRecord

  extend ActiveHash::Associations::ActiveRecordExtensions

  # アソシエーション
  belongs_to_active_hash :prefecture

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]

  include ActiveHash::Associations
  has_many :histrical_figures
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/histricalfigures_controller.rb
class HistricalfiguresController < ApplicationController
  def index
    
  end
  def new

  end
end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController

  def show
    render "/prefectures/new.html.haml"
  end
    # prefecture = Prefecture.find(params[:id])
    # @prefectureName = prefecture[:name] //うまく機能しない・足りないか間違っている


end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    render "layouts/index.html.haml"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/histricalfigures_helper.rb
module HistricalfiguresHelper
end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/histricalfigures/index.html.haml
.header
  = render partial: "render/header"

.figure-name
  織田信長
.figure-img
  = image_tag '織田信長.jpeg', :height => "500", :width => "500" 

.footer
  = render partial: "render/footer"

app/views/histricalfigures/new.html.haml
%h1 Histricalfigures#new
%p Find me in app/views/histricalfigures/new.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HistoricalFigure3
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/layouts/index.html.haml
.header
  = render partial: "render/header"

.transition-bar
  - if user_signed_in?
    = render "render/login_bar"
  - else
    = render "render/not_logged_bar"

.body
  .body__japan-map
    日本地図-地方別

    %script{:src => "//code.jquery.com/jquery-1.12.0.min.js"}
    = javascript_include_tag 'jquery.japan-map.min.js'
    :javascript
        var preflinklist = {
          "12":"/prefectures/12", //chiba,pathはURIパターンで記述。Prefixだとエラーが発生した。
          "13":"/prefectures/13", //tokyo
          "26":"/prefectures/26", //kyoto
          "27":"/prefectures/27", //osaka
          "23":"/prefectures/23"  //aichi, (戦国３英傑＜織田・徳川・豊臣＞)
        };

      $(function(){
          var areas = [
              {"code": 1 , "name":"北海道地方", "color":"#ca93ea", "hoverColor":"#e0b1fb", "prefectures":[1]},
              {"code": 2 , "name":"東北地方",   "color":"#a7a5ea", "hoverColor":"#d6d4fd", "prefectures":[2,3,4,5,6,7]},
              {"code": 3 , "name":"関東地方",   "color":"#84b0f6", "hoverColor":"#c1d8fd", "prefectures":[8,9,10,11,12,13,14]},
              {"code": 4 , "name":"北陸・甲信越地方",   "color":"#52d49c", "hoverColor":"#93ecc5", "prefectures":[15,16,17,18,19,20]},
              {"code": 4 , "name":"東海地方",   "color":"#77e18e", "hoverColor":"#aff9bf", "prefectures":[21,22,23,24]},
              {"code": 6 , "name":"近畿地方",   "color":"#f2db7b", "hoverColor":"#f6e8ac", "prefectures":[25,26,27,28,29,30]},
              {"code": 7 , "name":"中国地方",   "color":"#f9ca6c", "hoverColor":"#ffe5b0", "prefectures":[31,32,33,34,35]},
              {"code": 8 , "name":"四国地方",   "color":"#fbad8b", "hoverColor":"#ffd7c5", "prefectures":[36,37,38,39]},
              {"code": 9 , "name":"九州地方",   "color":"#f7a6a6", "hoverColor":"#ffcece", "prefectures":[40,41,42,43,44,45,46]},
              {"code":10 , "name":"沖縄地方",   "color":"#ea89c4", "hoverColor":"#fdcae9", "prefectures":[47]}
          ];

          $("#map-container").japanMap(
              {
                  areas  : areas,
                  selection : "prefecture",
                  borderLineWidth: 0.5,
                  drawsBoxLine : false,
                  movesIslands : true,
                  showsAreaName : true,
                  width: 760,
                  backgraoundColor: "red",
                  font : "MS Mincho",
                  fontSize : 12,
                  fontColor : "areaColor",
                  fontShadowColor : "black",
                onSelect : function(data){
                  if (data.code in preflinklist) {
                      console.log(preflinklist[data.code]);
                      location.href = preflinklist[data.code];
                  }
                }
              }
          );
      });

  .body__japan-map-insert
    #map-container

.footer
  = render partial: "render/footer"

app/views/prefectures/new.html.haml
.header
  = render partial: "render/header"

.prefecture-text
  愛知県
  -# = @prefectureName
.prefecture-img
  = image_tag 'Pre.23.aichi.png', :height => "850", :width => "850" 


.historical-figures
  .historical-figures__index
    .historical-figures__index__icon 
      = link_to image_tag("織田信長.jpeg", id:"img"), histricalfigures_index_path
      .historical-figures__index__icon--text
        織田信長
    .historical-figures__index__name
      .historical-figures__index__name--land-related
        ゆかりの地
      .historical-figures__index__name--add
        愛知県西部
      .historical-figures__index__name--another-name
        異名
      .historical-figures__index__name--another-name-one
        第六天魔王

  .historical-figures__index
    .historical-figures__index__icon
      = image_tag '豊臣秀吉.jpeg', id: "img"
      .historical-figures__index__icon--text
        豊臣秀吉
    .historical-figures__index__name
      .historical-figures__index__name--land-related
        ゆかりの地
      .historical-figures__index__name--add
        愛知県西部
      .historical-figures__index__name--another-name
        異名
      .historical-figures__index__name--another-name-one
        太閤殿下

  .historical-figures__index
    .historical-figures__index__icon 
      = image_tag '徳川家康.jpeg', id: "img"
      .historical-figures__index__icon--text
        徳川家康
    .historical-figures__index__name
      .historical-figures__index__name--land-related
        ゆかりの地
      .historical-figures__index__name--add
        愛知県東部
      .historical-figures__index__name--another-name
        異名
      .historical-figures__index__name--another-name-one
        東海一の弓取り


.footer
  = render partial: "render/footer"

app/views/render/_footer.html.haml
.footer
  app/views/devise/sessions/new.html.haml

app/views/render/_header.html.haml
.app-title
  .app-title__text
    地図から学ぶ日本の偉人たち

app/views/render/_login_bar.html.haml
.transition-bar__logout
  = link_to destroy_user_session_path(current_user), method: :delete, class: 'btn-sign-out' do
    ログアウト

app/views/render/_not_logged_bar.html.haml
.transition-bar__register
  = link_to new_user_registration_path do
    新規登録
.transition-bar__login
  = link_to new_user_session_path do
    ログイン
.transition-bar__guest
  = link_to "#" do
    ゲストログイン